version: '3'
services:
  php:
    build: ./docker/php-fpm
    volumes:
      - ./project:/var/www/project
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./project:/var/www/project
      - ./docker/nginx/project.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    volumes:
     - ./docker/databases:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 111111
    ports:
      - "3333:3306"